Fix System Tests for Product Bundles
workarea-commerce/workarea-nvy-theme pull request #12
Opened 2020-10-09 21:44 UTC by tubbo

When installing the NVY theme with the `workarea-product_bundles` plugin, the system tests for bundles fail because the UI in NVY is slightly different.

2020-10-12 12:23 UTC, bencrouse requested changes
I'd be interested to hear the story that led to this PR.

2020-10-12 12:23 UTC, bencrouse commented on test/system/workarea/storefront/categories_with_packages_system_test.decorator
> +      decorate CategoriesWithPackagesSystemTest, with: :bsi do
Can you update the `with:` for the plugin?

2020-10-12 13:44 UTC, tubbo commented
Oh, you will. Trust.   
  
  
  
    
  

  
  
>   
> On Oct 12, 2020 at 8:23 AM,  <Ben Crouse (mailto:notifications@github.com)>  wrote:
>   
>   
>   
>
>
>
>   
>
> @bencrouse  requested changes on this pull request.
>
>   
>
> I'd be interested to hear the story that led to this PR.
>
>     
>
> In   test/system/workarea/storefront/categories_with_packages_system_test.decorator (https://github.com/workarea-commerce/workarea-nvy-theme/pull/12#discussion_r503256787):
>
>   
>   >  @@ -0,0 +1,74 @@ +module Workarea + module Storefront + if Plugin.installed? :product_bundles + decorate CategoriesWithPackagesSystemTest, with: :bsi do  
>   
>
> Can you update the  with:  for the plugin?
>
>   
>
> —
>  You are receiving this because you authored the thread.
>  Reply to this email directly,   view it on GitHub (https://github.com/workarea-commerce/workarea-nvy-theme/pull/12#pullrequestreview-506568426), or   unsubscribe (https://github.com/notifications/unsubscribe-auth/AAA3TARHPVMBFUM66LLX3PLSKLYLZANCNFSM4SKSCK6Q).
>
>   
>

2020-10-12 14:34 UTC, tubbo commented on test/system/workarea/storefront/categories_with_packages_system_test.decorator
> +      decorate CategoriesWithPackagesSystemTest, with: :bsi do
lol what a giveaway

2020-10-12 21:48 UTC, tubbo commented
I can't get this to fail on my local...tried using the same seed and everything.

2020-10-13 12:37 UTC, bencrouse requested changes
Looks like some build failures...

2020-10-15 19:08 UTC, tubbo commented
Really not sure what the issue is here...I know NVY was never meant to be compatible with package products, and since family templates originate in that project, I wonder if we're going down a bad path here...

Strangely, the build in Bamboo CI passes when this is part of an app.

2020-10-16 12:35 UTC, bencrouse commented
Ok, let's side convo this at the standup.

2020-10-22 12:21 UTC, bencrouse approved these changes

2020-10-22 12:21 UTC, merged